name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    # Thêm dòng này để nói cho GitHub biết phải chui vào thư mục frontend để chạy lệnh
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: 1. Clone code từ GitHub về máy chủ ảo
        uses: actions/checkout@v3

      - name: 2. Cài đặt môi trường Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 3. Cài đặt các thư viện (NPM Install)
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: 4. Cài đặt Vercel CLI
        run: npm install --global vercel@latest

      - name: 5. Lấy thông tin dự án từ Vercel
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: 6. Build code Frontend
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: 7. Deploy lên Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
